#!/usr/bin/env bash
# setup-public.sh
# Copies mote project data files from temple-escape root subdirectories
# into the public/ folder so Vite can serve them as static assets.
#
# Run this after all agents have finished creating their files:
#   cd temple-escape && bash setup-public.sh

set -euo pipefail

BASE="$(cd "$(dirname "$0")" && pwd)"
PUBLIC="$BASE/public"

echo "Setting up public/ directory for Vite static serving..."

# Create target directories
mkdir -p "$PUBLIC/sheets" "$PUBLIC/entities" "$PUBLIC/scenes" "$PUBLIC/images"

# Copy sprite sheet JSON files
if [ -d "$BASE/sheets" ]; then
  cp -v "$BASE/sheets/"*.sprite.json "$PUBLIC/sheets/" 2>/dev/null || echo "  (no .sprite.json files found in sheets/)"
fi

# Copy entity definition JSON files
if [ -d "$BASE/entities" ]; then
  cp -v "$BASE/entities/"*.entity.json "$PUBLIC/entities/" 2>/dev/null || echo "  (no .entity.json files found in entities/)"
fi

# Copy scene/map JSON files
if [ -d "$BASE/scenes" ]; then
  cp -v "$BASE/scenes/"*.map.json "$PUBLIC/scenes/" 2>/dev/null || echo "  (no .map.json files found in scenes/)"
fi

# Copy project.mote.json if it exists at root
if [ -f "$BASE/project.mote.json" ]; then
  cp -v "$BASE/project.mote.json" "$PUBLIC/project.mote.json"
fi

# Copy images (generated by generate-sprites.py should already be in public/images/)
# But also pick up any images from a root images/ folder
if [ -d "$BASE/images" ] && [ "$(ls -A "$BASE/images/" 2>/dev/null)" ]; then
  cp -v "$BASE/images/"*.png "$PUBLIC/images/" 2>/dev/null || true
fi

# Also copy any sprite sheet image files referenced by the JSON
# Sprite sheet JSON files reference images with relative paths like "./temple-tiles.png"
# These images should be next to the JSON files or in images/
if [ -d "$BASE/sheets" ]; then
  for img in "$BASE/sheets/"*.png; do
    [ -f "$img" ] && cp -v "$img" "$PUBLIC/sheets/"
  done
fi

echo ""
echo "Done! Public directory structure:"
find "$PUBLIC" -type f | sort | head -50
echo ""
echo "Start the dev server with: cd $BASE && npx vite"
