// Auto-generated by Mote Map Editor
// Map: room_01
import { T } from '../TileIds.js';

export const ROOM_01 = {
  name: 'room_01',
  width: 16,
  height: 12,
  tileSize: 64,
  spawnPoint: { x: 8, y: 6 },
  tiles: [
  T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.CHEST,   T.CHEST,   T.CHEST,   T.CHEST,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.CHEST,   T.CHEST,   T.CHEST,   T.CHEST,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WATER,   T.WATER,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WATER,   T.WATER,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WATER,   T.WATER,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.PLANKS,   T.FLOOR,   T.FLOOR,   T.WATER,   T.WATER,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.PLANKS,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.CAMPFIRE,   T.CAMPFIRE,   T.CAMPFIRE,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL,
  T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,   T.WALL,
  ] as const,
};

// 默认导出，方便直接导入
export default ROOM_01;
