// Auto-generated by Mote Map Editor
// Map: room_02
import { T } from '../TileIds.js';

export const ROOM_02 = {
  name: 'room_02',
  width: 16,
  height: 12,
  tileSize: 64,
  spawnPoint: { x: 8, y: 6 },
  tiles: [
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.WALL,   T.WALL,   T.WALL,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.WALL,   T.WALL,   T.WALL,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.WALL,   T.WALL,   T.WALL,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.WALL,   T.WALL,   T.WALL,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.DOOR_OPEN,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.WALL,   T.WALL,   T.WALL,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  ] as const,
};

// 默认导出，方便直接导入
export default ROOM_02;
