// Auto-generated by Mote Map Editor
// Map: room_03
import { T } from '../TileIds.js';

export const ROOM_03 = {
  name: 'room_03',
  width: 16,
  height: 12,
  tileSize: 64,
  spawnPoint: { x: 8, y: 6 },
  tiles: [
  T.VOID,   T.VOID,   T.VOID,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.WALL_EDGE,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.VOID,   T.VOID,   T.FLOOR,
  T.VOID,   T.VOID,   T.WALL_EDGE,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.WALL_EDGE,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.FLOOR,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.WALL_EDGE,   T.WALL_EDGE,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.WALL_EDGE,   T.WALL_EDGE,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.WALL_EDGE,   T.WALL_EDGE,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.WALL_EDGE,   T.WALL_EDGE,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.WALL_EDGE,   T.WALL_EDGE,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,   T.VOID,
  ] as const,
};

// 默认导出，方便直接导入
export default ROOM_03;
